### ISSUE TITLE
Unable to have makeLogger in TaskR[Env, A]

### ISSUE THREAD

**Issue by wpoosanguansit** [mlangc/slf4zio#2]
Hi,

I am unable to have 

logger          <- makeLogger[Clazz]

in my code that is run in TaskR[Env, A] as makeLogger runs in ZIO[Any, Nothing, Nothing] .  Is there some setup we need to do to have types aligned?  Thanks.

**Comment by mlangc** [comment]
Thanks for your report. No setup should be necessary.  Unfortunately, apart from that, there is little I can say without further context. Can you post a minimal example, so that I can reproduce your issue?

**Comment by wpoosanguansit** [comment]
Thanks for your help.  At the moment I have to opt for getting the log through logs-cats you mentioned in your README.  The issue is the makeLogger[Clazz] would run in ZIO[Any, Nothing, Nothing] and that just does not compile for me because of using ZIO[Env, Throwable, A] where Env is my app's configuration setup.  If I have more time, I would create a snippet with code running in ZIO[Console, Throwable, A] and your logger to get the error I was getting as the example.  Thanks again for your help.

**Comment by mlangc** [comment]
Alright, if you find some time, I would really like to see the issue you had. I'm closing this for now. Feel free to reopen this ticket if appropriate.
