### ISSUE TITLE
Support for ZIO 2

### ISSUE THREAD

**Issue by erikvanoosten** [mlangc/slf4zio#7]
Hello, will ZIO 2 be supported?
Thanks!

**Comment by mlangc** [comment]
Sorry for responding this late: I've never worked with ZIO-2, and therefore I don't know how much effort it would be to port the library. I'll happily review & merge PRs related to this though!

**Comment by erikvanoosten** [comment]
To be honest, I am only interested in using the *IO methods in `Slf4jLoggerOps`. Those were migrated in a few minutes :)

**Comment by mlangc** [comment]
I'm not using ZIO in any of my projects at the moment, but if a PR related to ZIO 2 comes in, I'll happily review it and do my best to merge it.

**Comment by mlangc** [comment]
slf4zio-2.0.0 for ZIO-2.0 has just been released to Maven Central. Please file a bug if you encounter any issues.
